/*
 * This source file was generated by the Gradle 'init' task
 */
package irctcbackend;

import irctcbackend.entities.Train;
import irctcbackend.entities.User;
import irctcbackend.services.UserBookingServices;
import irctcbackend.utils.UserServicesUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) {

        System.out.println("Running Train booking system");

        Scanner scanner = new Scanner(System.in);
        int option = 0;

        UserBookingServices userBookingServices;

        try{
            userBookingServices = new UserBookingServices();
        } catch (IOException e) {
            System.out.println("There is something wrong!");
            return;
        }

        while (option != 7){
            System.out.println("Choose option ");
            String[] arr = {"1. Sign up","2. Login","3. Fetch Booking","4. Search Trains", "5. Book a seat", "6. Cancel my booking", "7. Exit the App"};
            for(String st: arr){
                System.out.println(st);
            }
            option = scanner.nextInt();
            Train trainSelectedFOrBooking = new Train();
            switch (option){
                case 1:
                    System.out.print("Enter the username to signup: ");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter your passwordToSignUp: ");
                    String passwordToSignUp = scanner.next();

                    User userToSignUp = new User(nameToSignUp,UserServicesUtil.hashedPassword(passwordToSignUp), passwordToSignUp, new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingServices.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.print("Enter the username to Login: ");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter your passwordToSignUp to Login: ");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin, UserServicesUtil.hashedPassword(passwordToLogin), passwordToLogin, new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingServices = new UserBookingServices(userToLogin);
                    } catch (IOException e) {
                       return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your booking");
                    userBookingServices.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source =scanner.nextLine();
                    System.out.println("Type your destination");
                    String destination = scanner.nextLine();
                    List<Train> trains = userBookingServices.getTrains(source, destination);

                    for(Train t:trains){
                        System.out.println("TrainID: " + t.getTrainId());
                        for (Map.Entry<String, String> entry:t.getStationTimes().entrySet()){
                            System.out.println("Station: " + entry.getKey() + "time: " + entry.getValue());
                        }
                    }
                    break;
                case 5:
                    System.out.println("Book a seats");
                    break;
                case 6:
                    System.out.println("Cancel train booking");
                    System.out.println("----------------------");
                    System.out.print("Put the trainId to cancel the booking: ");
                    String trainId = scanner.next();
                    boolean result =userBookingServices.cancelBooking(trainId);
                    System.out.println(result ? "The train is cancel" : "The train is available");
                    break;
            }
        }
    }
}
