/*
 * This source file was generated by the Gradle 'init' task
 */
package irctcbackend;

import irctcbackend.entities.Train;
import irctcbackend.entities.User;
import irctcbackend.services.UserBookingServices;
import irctcbackend.utils.UserServicesUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) {

        System.out.println("Running Train booking system");

        Scanner scanner = new Scanner(System.in);
        int option = 0;

        UserBookingServices userBookingServices;

        try{
            userBookingServices = new UserBookingServices();
        } catch (IOException e) {
            System.out.println("There is something wrong! " + e.getMessage());
            return;
        }

        while (option != 7){
            System.out.println("Choose option ");
            String[] arr = {"1. Sign up","2. Login","3. Fetch Booking","4. Search Trains", "5. Book a seat", "6. Cancel my booking", "7. Exit the App"};
            for(String st: arr){
                System.out.println(st);
            }
            option = scanner.nextInt();

            switch (option){
                case 1:
                    System.out.println("Enter the username to signup: ");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter your password To SignUp: ");
                    String passwordToSignUp = scanner.next();
                    userBookingServices.signUp(passwordToSignUp, nameToSignUp);
                    break;
                case 2:
                    System.out.println("Enter the username to Login: ");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter your password to Login: ");
                    String passwordToLogin = scanner.next();
                    userBookingServices.loginUser(nameToLogin, passwordToLogin);
                    break;
                case 3:
                    System.out.println("Fetching your booking");
                    userBookingServices.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source =scanner.next();
                    System.out.println("Type your destination");
                    String destination = scanner.next();
                    List<Train> trains = userBookingServices.getTrains(source, destination);
                    for(Train t:trains){
                        System.out.println("TrainID: " + t.getTrainId());
                        for (Map.Entry<String, String> entry:t.getStationTimes().entrySet()){
                            System.out.println("Station: " + entry.getKey() + "time: " + entry.getValue());
                        }
                    }
                    break;
                case 5:
                    System.out.println("------- Book a seats ----");
                    System.out.println("Enter source: ");
                    String bookedSource = scanner.next();
                    System.out.println("Enter destination: ");
                    String bookedDestination = scanner.next();
                    System.out.println("Enter the date of travel (DD/MM/YYYY - format): ");
                    String date = scanner.next();
                    Date dateOfTime =  UserServicesUtil.dateConversion(date);
                    userBookingServices.bookSeat(bookedSource,bookedDestination,dateOfTime);
                    break;
                case 6:
                    System.out.println("Cancel train booking");
                    System.out.println("----------------------");
                    System.out.print("Put the trainId to cancel the booking: ");
                    String trainId = scanner.next();
                    boolean result =userBookingServices.cancelBooking(trainId);
                    System.out.println(result ? "The train is cancel" : "The train is available");
                    break;
                case 7:
                    System.out.println("Thank you for choosing us");
                    break;
                default:
                    System.out.println("Please pick the correct one");
                    break;
            }
        }
    }
}
